;******************************************************************************
; constants.z80
; Contains labels for constants
;******************************************************************************

ROSS_MAJOR_VER: EQU 0
ROSS_MINOR_VER: EQU 0

CTC_CH0: EQU %0000                      ; Clock/Timer Channel 0 Port
CTC_CH1: EQU %0001                      ; Clock/Timer Channel 1 Port
CTC_CH2: EQU %0010                      ; Clock/Timer Channel 2 Port
CTC_CH3: EQU %0011                      ; Clock/Timer Channel 3 Port
PIO_AD: EQU %0100                       ; Parallel I/O Channel A Data
PIO_BD: EQU %0101                       ; Parallel I/O Channel B Data
PIO_AC: EQU %0110                       ; Parallel I/O Channel A Control
PIO_BC: EQU %0111                       ; Parallel I/O Channel B Control
LCD_C1: EQU %1000                       ; LCD Left Side Control
LCD_D1: EQU %1001                       ; LCD Left Side Data
LCD_C2: EQU %1010                       ; LCD Right Side Control
LCD_D2: EQU %1011                       ; LCD Right Side Data

CTC_TC: EQU 239                         ; Time Constant for 100 Hz
CTC_CMD: EQU %10100111                  ; Interrupt, 256 prescaler, TC follows

LCD_CMD_SETX: EQU %10111000 
LCD_CMD_SETY: EQU %11000000
LCD_CMD_SETZ: EQU %01000000
LCD_CMD_ON: EQU %00111111

FB_WIDTH_TILES: EQU 16
FB_HEIGHT_TILES: EQU 8
PX_PER_TILE: EQU 8

ERR_SUCCESS: EQU 0                      ; Success
ERR_FAILURE: EQU 1                      ; General failure
ERR_INVALID_ARG: EQU 2                  ; Invalid argument
ERR_NOT_FOUND: EQU 3                    ; Resource not found
ERR_EXISTS: EQU 4                       ; Resource already exists
ERR_OUT_OF_BOUNDS: EQU 5                ; Out of bounds access
ERR_IO: EQU 6                           ; I/O error
ERR_TIMEOUT: EQU 7                      ; Operation timed out
ERR_DIV_ZERO: EQU 8                     ; Division by zero
ERR_UNSUPPORTED: EQU 255                ; Unsupported operation
